Task_2:
NJord1408/invoicing-system-norbert-cieslik pull request #2
Opened 2024-03-25 20:44 UTC by NJord1408

2024-03-26 11:52 UTC, BartoszKamyszek requested changes
Brakuje testów, jak coś nie działa podczas builda to usuwaj przyczyny, a nie rzeczy które sprawdzają kod :)

2024-03-26 11:52 UTC, BartoszKamyszek commented on app/build.gradle
> +                minimum = 0.05
minimum powinno być ustawione na wartości z zadania

2024-03-26 11:52 UTC, BartoszKamyszek commented on app/build.gradle
> +                minimum = 0.05
jak wyżej

2024-03-26 11:52 UTC, BartoszKamyszek commented on app/build.gradle
> +//}
dlaczego zakomentowane?

2024-03-26 11:52 UTC, BartoszKamyszek commented on .github/workflows/main.yaml
> +    branches: [ task_* ]
nie odpala Ci się build na github, sprawdź konfigurację, może nazwy brancha nie matchują się z tym jak Ty je nazywasz

2024-03-26 11:52 UTC, BartoszKamyszek commented on app/src/main/java/pl/futurecollars/invoicing/db/Database.java
> +    int save(Invoice invoice);
linijka

2024-03-26 11:52 UTC, BartoszKamyszek commented on app/src/main/java/pl/futurecollars/invoicing/db/memory/InMemoryDatabase.java
> +
linijka, odpal checkstyle żeby tego uniknąć

2024-03-26 11:52 UTC, BartoszKamyszek commented on app/src/main/java/pl/futurecollars/invoicing/db/memory/InMemoryDatabase.java
> +
linijka

2024-03-26 11:52 UTC, BartoszKamyszek commented on app/src/main/java/pl/futurecollars/invoicing/db/memory/InMemoryDatabase.java
> +
linijka

2024-03-26 18:11 UTC, NJord1408 commented on app/build.gradle
> +                minimum = 0.05
Już poprawiłem zasugerowałem się wykładem nr. 3

2024-03-26 18:12 UTC, NJord1408 commented on app/build.gradle
> +//}
...szczerze mówiąc sam nie wiem. Poprawione oraz wynikające z niego błędy.

2024-03-26 18:13 UTC, NJord1408 commented on app/src/main/java/pl/futurecollars/invoicing/db/Database.java
> +    int save(Invoice invoice);
Poprawione

2024-03-26 18:13 UTC, NJord1408 commented on app/src/main/java/pl/futurecollars/invoicing/db/memory/InMemoryDatabase.java
> +
Poprawione zgodnie ze standardami checkstyle

2024-03-26 18:14 UTC, NJord1408 commented on app/src/main/java/pl/futurecollars/invoicing/db/memory/InMemoryDatabase.java
> +
Poprawione

2024-03-26 18:14 UTC, NJord1408 commented on app/src/main/java/pl/futurecollars/invoicing/db/memory/InMemoryDatabase.java
> +
Poprawione

2024-03-28 20:07 UTC, BartoszKamyszek approved these changes

2024-03-28 20:09 UTC, merged